apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: aaa
          command:
            - sh
          ports:
            - name: http
              protocol: TCP
